#!/bin/bash
cat << EOL | fdisk /dev/sda
n
p



w
EOL

mkfs.ext4 /dev/sda1
mount /dev/sda1 /mnt
pacstrap /mnt base base-devel linux linux-firmware dhcpcd links vim grub
genfstab /mnt >> /mnt/etc/fstab

cat << EOF | arch-chroot /mnt
(echo '1qaz2wsx'; echo '1qaz2wsx') | passwd
sed -i 's/#en_US.UTF-8/en_US.UTF-8/g' /etc/locale.gen
locale-gen
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
EOF
